spring.application.name=backend
# Pengaturan Koneksi Database
spring.datasource.url=jdbc:postgresql://localhost:5432/animarum_db
spring.datasource.username=postgres
spring.datasource.password=Kemangpratama06

# Pengaturan JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true